recommendation/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

# To display images
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

store/urls.py
from store.forms import LoginForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib import admin


# django admin costumization
admin.site.site_header = 'Amogle Dashboard'
admin.site.site_title = 'Welcome Rick Sanchez'
admin.site.index_title = 'Welcome to the Citadel Of Ricks'


app_name = 'store'


urlpatterns = [
    path('', views.home, name="home"),
    # URL for Cart and Checkout
    path('add-to-cart/', views.add_to_cart, name="add-to-cart"),
    path('remove-cart/<int:cart_id>/', views.remove_cart, name="remove-cart"),
    path('remove-order/<int:order_id>/',
         views.remove_order, name="remove-order"),
    path('remove-fav/<int:fav_id>/',
         views.remove_fav, name="remove-fav"),
    path('plus-cart/<int:cart_id>/', views.plus_cart, name="plus-cart"),
    path('minus-cart/<int:cart_id>/', views.minus_cart, name="minus-cart"),
    path('cart/', views.cart, name="cart"),
    path('chkout/', views.chkout, name="chkout"),
    path('orders/', views.orders, name="orders"),
    path('contact/', views.contact, name="contact"),
    path('rate/', views.rate, name="rate"),
    #     path('liked/', views.like_unlike_post, name='like-post-view'),


    path('add-to-favourate/', views.add_to_favourate, name="add-to-favourate"),
    path('fav/', views.fav, name="fav"),

    # url for blog
    path('blog/', views.blog, name="blog"),
    path('blog/<slug:slug>/', views.post_detail, name="post-detail"),
    path('comment/<slug:slug>/', views.comment, name="comment"),

    # URL for Products
    path('product/<slug:slug>/', views.detail, name="product-detail"),
    path('categories/', views.all_categories, name="all-categories"),
    path('<slug:slug>/', views.category_products, name="category-products"),

    path('shop/', views.shop, name="shop"),

    # URL for Authentication
    path('accounts/register/', views.RegistrationView.as_view(), name="register"),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='account/login.html',
         authentication_form=LoginForm), name="login"),
    path('accounts/profile/', views.profile, name="profile"),
    path('accounts/add-address/', views.AddressView.as_view(), name="add-address"),
    path('accounts/remove-address/<int:id>/',
         views.remove_address, name="remove-address"),
    path('accounts/logout/',
         auth_views.LogoutView.as_view(next_page='store:login'), name="logout"),

    path('accounts/password-change/', auth_views.PasswordChangeView.as_view(template_name='account/password_change.html',
         form_class=PasswordChangeForm, success_url='/accounts/password-change-done/'), name="password-change"),
    path('accounts/password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='account/password_change_done.html'), name="password-change-done"),

    path('accounts/password-reset/', auth_views.PasswordResetView.as_view(template_name='account/password_reset.html', form_class=PasswordResetForm, success_url='/accounts/password-reset/done/'),
         name="password-reset"),  # Passing Success URL to Override default URL, also created password_reset_email.html due to error from our app_name in URL
    path('accounts/password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='account/password_reset_done.html'), name="password_reset_done"),
    path('accounts/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html',
         form_class=SetPasswordForm, success_url='/accounts/password-reset-complete/'), name="password_reset_confirm"),  # Passing Success URL to Override default URL
    path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='account/password_reset_complete.html'), name="password_reset_complete"),

    path('product/test/', views.test, name="test"),
    path('verify_payment', views.verify_payment, name='verify_payment')


]

store/views.py
from os import stat
import re
from site import addusersitepackages
from tkinter import N
import django
from django.contrib.auth.models import User
from store.models import Address, Cart, Category, Order, Product
from django.shortcuts import redirect, render, get_object_or_404
from .forms import RegistrationForm, AddressForm
from django.contrib import messages
from django.views import View
import decimal
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator  # for Class Based Views
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, JsonResponse
import requests
import json
import sys
from subprocess import run, PIPE
from django.http import HttpResponseRedirect
from .models import *
from .forms import *
from django.template.loader import render_to_string, get_template
from django.core.mail import EmailMessage, send_mail
from django.conf import settings
from django.template import Context
from django.views.generic import ListView
from django.db.models import Q
import random
from store.script import *
from ast import literal_eval as make_tuple


# Create your views here.


def home(request):
    user_id = request.user.id
    headers = {
        'content-type': "multipart/form-data",
        'cache-control': "no-cache",

    }
    user_id = user_id
    print(user_id)
    if user_id:
        categories = Category.objects.filter(
            is_active=True, is_featured=True)[:3]
        products = Product.objects.order_by('?')[:8]

        url = "http://127.0.0.1:5000/recommend"
        payload = {'user_id': user_id}
        responses = requests.request("POST", url, data=payload)
        print(responses)

        response = json.loads(responses.text)
        respnses_tuple = make_tuple(response)
        context = list()

        for user_id in respnses_tuple:
            try:
                recommended = Product.objects.get(id=user_id)
                context.append(recommended)
            except:
                pass
        # contexts = Moviess.objects.all()
        # query = request.GET.get('q')
        context = {
            'context': context,
            'categories': categories,
            'products': products,
        }
        return render(request, 'store/index.html', context)
    else:
        categories = Category.objects.filter(
            is_active=True, is_featured=True)[:3]
        products = Product.objects.order_by('?')[:8]
        contexts = {
            'message': 'Please log in firts.',
            'categories': categories,
            'products': products,
        }

        return render(request, 'store/index.html', contexts)


def detail(request, slug):

    product = get_object_or_404(Product, slug=slug)
    related_products = Product.objects.exclude(id=product.id).filter(
        is_active=True, category=product.category)[:4]

    headers = {
        'content-type': "multipart/form-data",
        'cache-control': "no-cache",
    }

    recommend = None
    obj_list = []
    product_name = product.title
    print(product_name)
    if product_name:
        url = "http://127.0.0.1:5000/get_recommendation"
        payload = {'product_name': product_name}
        responses = requests.request("POST", url, data=payload)
        print(responses)

        response = json.loads(responses.text)

        print(response)

        value = tuple(response.values())
        print(value)
        for x in value:
            try:
                '''
                    filtering the products database by product title, with respect to
                    the obtained flask recommendation api.
                '''
                recommend = Product.objects.get(title=x)
                obj_list.append(recommend)
            except:

                pass

    context = {

        'product': product,
        'related_products': related_products,
        'recommendated': obj_list

    }
    return render(request, 'store/detail.html', context)


def all_categories(request):
    categories = Category.objects.filter(is_active=True)
    return render(request, 'store/categories.html', {'categories': categories})

# # /////////    NORMAL QUERY SEARCH FOR PRODUCTS    /////////

# def category_products(request, slug):
#     if 'q' in request.GET:
#         q = request.GET['q']
#         category = get_object_or_404(Category, slug=slug)
#         products = Product.objects.filter(title__icontains=q)
#         categories = Category.objects.filter(is_active=True)
#         context = {
#             'category': category,
#             'products': products,
#             'categories': categories,
#         }
#     else:
#         category = get_object_or_404(Category, slug=slug)
#         products = Product.objects.filter(is_active=True, category=category)
#         categories = Category.objects.filter(is_active=True)
#         context = {
#             'category': category,
#             'products': products,
#             'categories': categories,
#         }
#     return render(request, 'store/category_products.html', context)


# //////////////// SEARCH WITH COMMAS AND SAPCING ////////////


def category_products(request, slug):

    if 'q' in request.GET:
        query = request.GET.get('q')
        products = None
        count_search = None
        if query:

            for ing in query.split():

                products = Product.objects.filter(
                    Q(title__icontains=ing) | Q(short_description__icontains=ing))
                count_search = products.count()
                print(ing)
        category = get_object_or_404(Category, slug=slug)
        categories = Category.objects.filter(is_active=True)

        context = {
            'category': category,
            'products': products,
            'categories': categories,
            'count_search': count_search,
            'query': query,
        }

    else:
        category = get_object_or_404(Category, slug=slug)
        products = Product.objects.filter(is_active=True, category=category)
        categories = Category.objects.filter(is_active=True)
        context = {
            'category': category,
            'products': products,
            'categories': categories,
        }
    return render(request, 'store/category_products.html', context)


# Authentication Starts Here

class RegistrationView(View):
    def get(self, request):
        form = RegistrationForm()
        return render(request, 'account/register.html', {'form': form})

    def post(self, request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            messages.success(
                request, "Congratulations! Registration Successful!")
            form.save()
        return render(request, 'account/register.html', {'form': form})


@ login_required
def profile(request):
    addresses = Address.objects.filter(user=request.user)
    orders = Order.objects.filter(user=request.user)
    return render(request, 'account/profile.html', {'addresses': addresses, 'orders': orders})


@ method_decorator(login_required, name='dispatch')
class AddressView(View):
    def get(self, request):
        form = AddressForm()
        return render(request, 'account/add_address.html', {'form': form})

    def post(self, request):
        form = AddressForm(request.POST)
        if form.is_valid():
            user = request.user
            locality = form.cleaned_data['locality']
            city = form.cleaned_data['city']
            state = form.cleaned_data['state']
            reg = Address(user=user, locality=locality, city=city, state=state)
            reg.save()
            messages.success(request, "New Address Added Successfully.")
        return redirect('store:profile')


@ login_required
def remove_address(request, id):
    a = get_object_or_404(Address, user=request.user, id=id)
    a.delete()
    messages.success(request, "Address removed.")
    return redirect('store:profile')


@ login_required
def add_to_cart(request):
    user = request.user
    product_id = request.GET.get('prod_id')
    product = get_object_or_404(Product, id=product_id)
    # Check whether the Product is alread in Cart or Not
    item_already_in_cart = Cart.objects.filter(product=product_id, user=user)
    if item_already_in_cart:
        cp = get_object_or_404(Cart, product=product_id, user=user)
        cp.quantity += 1
        cp.save()
    else:
        Cart(user=user, product=product).save()

    return redirect('store:cart')


@ login_required
def add_to_favourate(request):
    user = request.user
    product_id = request.GET.get('prod_id')
    product = get_object_or_404(Product, id=product_id)

    Fav(user=user, product=product).save()

    return redirect('store:fav')


def fav(request):
    user = request.user
    fav_products = Fav.objects.filter(user=user)
    context = {
        'fav_products': fav_products,
    }
    return render(request, 'store/fav.html', context)


@ login_required
def cart(request):
    user = request.user
    cart_products = Cart.objects.filter(user=user)

    # Display Total on Cart Page
    amount = decimal.Decimal(0)
    shipping_amount = decimal.Decimal(10)
    # using list comprehension to calculate total amount based on quantity and shipping
    cp = [p for p in Cart.objects.all() if p.user == user]
    if cp:
        for p in cp:
            temp_amount = (p.quantity * p.product.price)
            amount += temp_amount

    # Customer Addresses
    addresses = Address.objects.filter(user=user)

    context = {
        'cart_products': cart_products,
        'amount': amount,
        'shipping_amount': shipping_amount,
        'total_amount': amount + shipping_amount,
        'addresses': addresses,

    }
    return render(request, 'store/cart.html', context)


@ login_required
def remove_cart(request, cart_id):
    if request.method == 'GET':
        c = get_object_or_404(Cart, id=cart_id)
        c.delete()

templates/store/add_comment.html
{% load tailwind_tags %}
{% load static %}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block metatitle %}Product Recommendation System{% endblock metatitle %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
	{% tailwind_css %} 
</head>
<header>
	<!-- Navbar -->
	<nav class="navbar navbar-expand-lg shadow-md py-2 bg-white relative flex items-center w-full justify-between">
	  <div class="px-6 w-full flex flex-wrap items-center justify-between">
		<div class="flex items-center">
		  <button
			class="navbar-toggler border-0 py-3 lg:hidden leading-none text-xl bg-transparent text-gray-600 hover:text-gray-700 focus:text-gray-700 transition-shadow duration-150 ease-in-out mr-2"
			type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContentY"
			aria-controls="navbarSupportedContentY" aria-expanded="false" aria-label="Toggle navigation">
			<svg aria-hidden="true" focusable="false" data-prefix="fas" class="w-5" role="img"
			  xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
			  <path fill="currentColor"
				d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z">
			  </path>
			</svg>
		  </button>
		</div>
		<div class="navbar-collapse collapse grow items-center" id="navbarSupportedContentY">
		  <ul class="navbar-nav mr-auto lg:flex lg:flex-row">
			<li class="nav-item">
			  <a class="nav-link block pr-2 lg:px-2 py-2 text-gray-600 hover:text-gray-700 focus:text-gray-700 transition duration-150 ease-in-out font-bold "
				href="{% url 'store:home' %}" data-mdb-ripple="true" data-mdb-ripple-color="light">Home</a>
			</li>
			
            <li class="nav-item">
                <a class="nav-link block pr-2 lg:px-2 py-2 text-gray-600 hover:text-gray-700 focus:text-gray-700 transition duration-150 ease-in-out font-bold"
                  href="{% url 'store:blog' %}" data-mdb-ripple="true" data-mdb-ripple-color="light">Blog Page</a>
              </li>
              <li class="nav-item">
                <a class="nav-link block pr-2 lg:px-2 py-2 text-gray-600 hover:text-gray-700 focus:text-gray-700 transition duration-150 ease-in-out font-bold"
                  href="{% url 'store:all-categories' %}" data-mdb-ripple="true" data-mdb-ripple-color="light">Categories</a>
              </li>
		
		  </ul>
		</div>
	  </div>
	</nav>
</header>
<body>
    <!-- comment form -->
    <div class="flex justify-center ...">
    <h1 class="font-medium leading-tight text-5xl mt-0 mb-2 text-blue-600">Add Your Comments</h1>
    </div>
    
    <div class="flex justify-center ...">
       
<div class="flex mx-auto items-center justify-center shadow-lg mt-56 mx-8 mb-4 max-w-lg">
    <form class="w-full max-w-xl bg-white rounded-lg px-4 pt-2" method='POST'>
        {% csrf_token %}
       <div class="flex flex-wrap -mx-3 mb-6">
          <h2 class="px-4 pt-3 pb-2 text-gray-800 text-lg">Add a new comment</h2>
          <div class="w-full md:w-full px-3 mb-2 mt-2">
             <textarea class="bg-gray-100 rounded border border-gray-400 leading-normal resize-none w-full h-20 py-2 px-3 font-medium placeholder-gray-700 focus:outline-none focus:bg-white" name="body" placeholder='Type Your Comment' required></textarea>
          </div>
          <div class="w-full md:w-full flex items-start md:w-full px-3">
             <div class="flex items-start w-1/2 text-gray-700 px-2 mr-auto">
                <svg fill="none" class="w-5 h-5 text-gray-600 mr-1" viewBox="0 0 24 24" stroke="currentColor">
                   <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/>
                </svg>
                <p class="text-xs md:text-sm pt-px">Leave Your Thoughts</p>
             </div>
             <div class="-mr-1">
                <input type='submit' class="bg-white text-blue-700 font-medium py-1 px-4 border border-gray-400 rounded-lg tracking-wide mr-1 hover:bg-gray-100" value='Post Comment'  >
             </div>
          </div>
       </form>
    </div>
 </div>
</div>
</body>
</html>

templates/store/cart.html
{% extends 'base.html' %} {% load static %} {% load humanize %}


{% block content%}
<div class="container">
  <!-- HERO SECTION-->
  <section class="py-5 bg-light">
    <div class="container">
      <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
        <div class="col-lg-6">
          <h1 class="h2 text-uppercase mb-0">Cart</h1>
        </div>
        <div class="col-lg-6 text-lg-right">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb justify-content-lg-end mb-0 px-0">
              <li class="breadcrumb-item"><a href="index.html">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Cart</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section>

  {% if cart_products %}
  <section class="py-5">
    <h2 class="h5 text-uppercase mb-4">Shopping cart</h2>

    {% include 'partials/_messages.html' %}

    <div class="row">
      <div class="col-lg-8 mb-4 mb-lg-0">
        <!-- CART TABLE-->
        <div class="table-responsive mb-4">
          <table class="table">
            <thead class="bg-light">
              <tr>
                <th class="border-0" scope="col">
                  <strong class="text-small text-uppercase">Product</strong>
                </th>
                <th class="border-0" scope="col">
                  <strong class="text-small text-uppercase">Price</strong>
                </th>
                <th class="border-0" scope="col">
                  <strong class="text-small text-uppercase">Quantity</strong>
                </th>
                <th class="border-0" scope="col">
                  <strong class="text-small text-uppercase">Total</strong>
                </th>
                <th class="border-0" scope="col"></th>
              </tr>
            </thead>
            <tbody>
              {% for cart_product in cart_products %}
              <tr>
                <th class="pl-0 border-0" scope="row">
                  <div class="media align-items-center">
                    {% if cart_product.product.product_image %}
                    <a
                      class="reset-anchor d-block animsition-link"
                      href="{% url 'store:product-detail' cart_product.product.slug %}"
                      ><img
                        src="{{cart_product.product.product_image}}"
                        alt="{{cart_product.product.title}}"
                        width="70"
                    /></a>
                    {% else %}
                    <a
                      class="reset-anchor d-block animsition-link"
                      href="{% url 'store:product-detail' cart_product.product.slug %}"
                      ><img
                        src="{% static 'img/product-detail-3.jpg' %}"
                        alt="{{cart_product.product.title}}"
                        width="70"
                    /></a>
                    {% endif %}

                    <div class="media-body ml-3">
                      <strong class="h6"
                        ><a
                          class="reset-anchor animsition-link"
                          href="{% url 'store:product-detail' cart_product.product.slug %}"
                          >{{cart_product.product.title}}</a
                        ></strong
                      >
                    </div>
                  </div>
                </th>
                <td class="align-middle border-0">
                  <p class="mb-0 small">${{cart_product.product.price}}</p>
                </td>
                <td class="align-middle border-0">
                  <div
                    class="border d-flex align-items-center justify-content-between px-3"
                  >
                    <span
                      class="small text-uppercase text-gray headings-font-family"
                      >Quantity</span
                    >
                    <div class="quantity">
                      <a
                        href="{% url 'store:minus-cart' cart_product.id %}"
                        class="dec-btn p-0 ml-2"
                        ><i class="fas fa-minus"></i
                      ></a>
                     
                      <input
                        class="form-control form-control-sm border-0 shadow-0 p-0"
                        type="text"
                        value="{{cart_product.quantity}}"
                      />
                     
                      <a
                        href="{% url 'store:plus-cart' cart_product.id %}"
                        class="inc-btn p-0"
                        ><i class="fas fa-plus"></i
                      ></a>
                    </div>
                  </div>
                </td>
                <td class="align-middle border-0">
                  <p class="mb-0 small">
                    ${{cart_product.total_price|intcomma}}
                  </p>
                </td>
                <td class="align-middle border-0">
                  <a
                    class="reset-anchor"
                    href="{% url 'store:remove-cart' cart_product.id %}"
                    ><i class="fas fa-trash-alt small text-muted"></i
                  ></a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- CART NAV-->
        <div class="bg-light px-4 py-3">
          <div class="row align-items-center text-center">
            <div class="col-md-6 mb-3 mb-md-0 text-md-left">
              <a
                class="btn btn-link p-0 text-dark btn-sm"
                href="{% url 'store:home' %}"
                ><i class="fas fa-long-arrow-alt-left mr-2"> </i>Continue
                shopping</a
              >
            </div>
            <div class="col-md-6 text-md-right">
              
              <a class="btn btn-outline-dark btn-sm" href="{% url 'store:orders' %}"
                >Order Details<i
                  class="fas fa-long-arrow-alt-right ml-2"
                ></i
              ></a>
            </div>
          </div>
        </div>
      </div>
      <!-- ORDER TOTAL-->
      <div class="col-lg-4">
        <div class="card border-0 rounded-0 p-lg-4 bg-light">
          <div class="card-body">
            <h5 class="text-uppercase mb-4">Cart total</h5>
            <ul class="list-unstyled mb-0">
              <li class="d-flex align-items-center justify-content-between">
                <strong class="text-uppercase small font-weight-bold"
                  >Subtotal</strong
                ><span class="text-muted small">${{amount|intcomma}}</span>
              </li>
              <li class="d-flex align-items-center justify-content-between">
                <strong class="text-uppercase small font-weight-bold"
                  >Shipping Charge</strong
                ><span class="text-muted small">+ ${{shipping_amount}}</span>
              </li>
              <li class="border-bottom my-2"></li>
              <li
                class="d-flex align-items-center justify-content-between mb-4"
              >
                <strong class="text-uppercase small font-weight-bold"
                  >Total</strong
                ><span>${{total_amount|intcomma}}</span>
              </li>
              <li>
              </li>
            </ul>

            <h5 class="text-uppercase my-5">Select Shipping Address</h5>

            <form action="{% url 'store:chkout' %}" id="myform">

              {% if addresses %}
                {% for address in addresses %}
                  <div class="mb-3">
                  <input type="radio" name="address" value="{{address.id}}"> <strong>Address {{forloop.counter}}</strong> <br>
                  ( {{address.locality}}, {{address.city}}, {{address.state}} )
                  </div>
                {% endfor %}
              {% endif %}
              <button type="submit" class="btn btn-dark btn-lg btn-outline-dark" type="submit"></i>Cash on Delivery</button>

            </form>
            <br/>
              <!-- Set up a container element for the button -->
              <div class="text-end" id="payment-button">
                <a class="btn btn-outline-dark btn-sm" 
                >Pay With Khalti</a>  
              </div>
            </br>

              {% comment %} For Cash on Delivery {% endcomment %}
              
            
          </div>
        </div>
      </div>
    </div>
  </section>

  {% else %}

  <div class="text-center py-5">
    <h3 class="mb-3">Your cart is empty.</h3>
    <a href="{% url 'store:home' %}"
      ><i class="fas fa-long-arrow-alt-left mr-2"> </i>Continue shopping</a
    >
  </div>

  {% endif %}
</div>
{% endblock content %} {% block payment-gateway %}
<!-- Include the PayPal JavaScript SDK -->
<script src="https://khalti.s3.ap-south-1.amazonaws.com/KPG/dist/2020.12.17.0.0.0/khalti-checkout.iffe.js"></script>

<script>
   function verifyPayment(payload) {
    $.ajax({
      url: "{% url 'store:verify_payment' %}",
      type: "POST",
      data: payload,
      dataType: "json",
      success: function (response) {
        alert(response);
      },
      error: function (error) {
        alert(error.responseJSON["message"]);
      },
    });
  } 
  
  var config = {
    // replace the publicKey with yours
    publicKey: "test_public_key_b8af7d684b334617af3c6939a3172f10",
    productIdentity: "1234567890",
    productName: "Dragon",
    productUrl: "http://127.0.0.1:8000/",
    paymentPreference: [
      "KHALTI",
      "EBANKING",
      "MOBILE_BANKING",
      "CONNECT_IPS",
      "SCT",
    ],
    eventHandler: {
      onSuccess(payload) {
        // hit merchant api for initiating verfication
        console.log(payload);
      },
      onError(error) {
        console.log(error);
      },
      onClose() {
        console.log("widget is closing");
      },
    },
  };

  var checkout = new KhaltiCheckout(config);
  var btn = document.getElementById("payment-button");
  btn.onclick = function () {
    // minimum transaction amount must be 10, i.e 1000 in paisa.
    checkout.show({ amount: {{total_amount}} });
  };
</script>
{% endblock payment-gateway %}

templates/store/fav.html
{% extends 'base.html' %} {% load static %} 

{% block content%}

          <div class =container>
          <h2 class="h5 text-uppercase mb-4">Favourate products</h2>
          <div class="row">

            {% if fav_products %}
              {% for f in fav_products %}
              
                <!-- PRODUCT-->
                <div class="col-lg-3 col-sm-6">
                  <div class="product text-center skel-loader">
                    <div class="d-block mb-3 position-relative">
                        {% if f.product.product_image %}
                          <img class="img-fluid w-100" src="{{f.product.product_image}}" alt="{{f.product.title}}">
                        {% else %}
                        <img class="img-fluid w-100" src="{% static 'img/product-1.jpg' %}" alt="{{f.product.title}}">
                        {% endif %}
                      </a>

                      <div class="product-overlay">
                        <ul class="mb-0 list-inline">
                          
                          <form action="{% url 'store:add-to-cart' %}">
                            <input type="hidden" name="prod_id" value="{{f.product.id}}" id="f.product_id">
                            <li class="list-inline-item m-0 p-0"></li>
                            <button type="submit" class="btn btn-sm btn-danger">Add to Cart</button>
                          </li>
                          </form>
                          <a
                            class="reset-anchor"
                            href="{% url 'store:remove-fav' f.id %}"
                            ><i class="fas fa-trash-alt small text-muted"></i
                          ></a>


                          
                        </ul>
                      </div>
                    </div>
                    <h6> <a class="reset-anchor">{{ f.product.title }}</a></h6>
                    <p class="small text-muted">${{f.product.price}}</p>
                    
                  </div>
                </div>

              {% endfor %}
            {% endif %}
            </div>

{% endblock content %}